### ISSUE TITLE
await import('ass-compiler') 没有导出任何函数

### ISSUE THREAD

**Issue by ShenHongFei** [weizhenye/ass-compiler#18]
```ts
await import('ass-compiler')
```

返回
```
[Module: null prototype] {

}
```

**Comment by ShenHongFei** [comment]
v0.1.12 版本

**Comment by weizhenye** [comment]
你是使用什么构建工具的？目前 [package.json](https://github.com/weizhenye/ass-compiler/blob/7fe5e67df2816c1c3b9717a00e910e9d3c5d50f1/package.json#L6-L7) 中设置了 module 字段是直接引用 Module 格式的，dist 中构建后的是 UMD 格式，看着像是构建工具引错文件了。

<img width="652" alt="image" src="https://github.com/user-attachments/assets/c968decb-f0f0-466f-a3e6-5b0f96c8247c">

**Comment by ShenHongFei** [comment]
直接在 node.js 中通过 import 导入

**Comment by weizhenye** [comment]
`v0.1.13` 应该可以了
