### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by JoshuaWalsh** [weizhenye/ass-compiler#7]
Hi,

I'm getting a similar error message to #6, but I'm already using 0.1.2.

Here is the subtitle file that's causing problems: 
[Beastars S02E09.zip](https://github.com/weizhenye/ass-compiler/files/6101462/Beastars.S02E09.zip)

Thanks very much for this excellent library, it's really helping me out with my [subtitle-indexer](https://github.com/JoshuaWalsh/subtitle-indexer) project!

**Comment by weizhenye** [comment]
fixed in `v0.1.3`
