### ISSUE TITLE
[BUG] Style decompiler is case sensitive

### ISSUE THREAD

**Issue by Deathspike** [weizhenye/ass-compiler#8]
I encountered the following `.ass` style header in production:

    Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,Strikeout,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding

The `Strikeout` property in this style header is not written as `StrikeOut`.
When using `ass-compiler` to decompile this, `StrikeOut` will be undefined.
And when serializing again, `StrikeOut` is undefined, making the `.ass` invalid.

The parsing of headers should be using case-insensitive comparisons.
I'd be happy to e-mail you the `.ass` file if that helps.

**Comment by weizhenye** [comment]
fixed in `v0.1.4`

**Comment by Deathspike** [comment]
Works perfectly. Thanks!
